import { motion } from "framer-motion";
import { motion } from "framer-motion";
import { motion } from "framer-motion";
import { motion } from "framer-motion";
import { motion } from "framer-motion";
import Image from "next/image";
import Image from "next/image";
import Image from "next/image";
import Image from "next/image";
import Image from "next/image";
import React, { useMemo } from "react";
import React, { useMemo } from "react";
import React, { useMemo } from "react";
import React, { useMemo } from "react";
import React, { useMemo } from "react";
import Image from "next/image";
import React, { useMemo } from "react";
import getScrollAnimation from "../utils/getScrollAnimation";
import getScrollAnimation from "../utils/getScrollAnimation";
import getScrollAnimation from "../utils/getScrollAnimation";
import getScrollAnimation from "../utils/getScrollAnimation";
import getScrollAnimation from "../utils/getScrollAnimation";
import ScrollAnimationWrapper from "./Layout/ScrollAnimationWrapper";
import ScrollAnimationWrapper from "./Layout/ScrollAnimationWrapper";
import ScrollAnimationWrapper from "./Layout/ScrollAnimationWrapper";
import ScrollAnimationWrapper from "./Layout/ScrollAnimationWrapper";
import ScrollAnimationWrapper from "./Layout/ScrollAnimationWrapper";
import Testimoni from "./Testimoni";
import Testimoni from "./Testimoni";
import Testimoni from "./Testimoni";
import Testimoni from "./Testimoni";
import Testimoni from "./Testimoni";
import ButtonOutline from "./misc/ButtonOutline.";
import ButtonOutline from "./misc/ButtonOutline.";
import ButtonOutline from "./misc/ButtonOutline.";
import ButtonOutline from "./misc/ButtonOutline.";
import ButtonOutline from "./misc/ButtonOutline.";
import ButtonPrimary from "./misc/ButtonPrimary";
import ButtonPrimary from "./misc/ButtonPrimary";
import ButtonPrimary from "./misc/ButtonPrimary";
import ButtonPrimary from "./misc/ButtonPrimary";
import ButtonPrimary from "./misc/ButtonPrimary";
import getScrollAnimation from "../../utils/getScrollAnimation";
import ScrollAnimationWrapper from "../Layout/ScrollAnimationWrapper";